version: "3.7"
services:
    bot:
        container_name: phantomknight
        image: phantomknight/phantomknight:latest
        restart: unless-stopped
        volumes:
            - phantomknight-logs:/app/logs
        env_file:
            - .env
        environment:
            - token=$token
            - mongodbUrl=$mongodbUrl
            - clientId=$clientId
            - guildId=$guildId
            - topggtoken= $topggtoken
        stdin_open: true
        tty: true
        networks:
            - phantomknight
    client:
        container_name: PhantomKnight-Client
        image: phantomknight/phantomknight-client:latest
        restart: unless-stopped
        depends_on:
            - bot
        ports:
            - "3000:3000"
        networks:
            - phantomknight
volumes:
    phantomknight-logs:

networks:
    frontend:
        name: phantomknight
