version: "3.7"
services:
    mongodb:
        image: docker.io/bitnami/mongodb:4.4
        env_file: ./.env
        ports:
            - $mongodbLocalPort:$mongodbDockerPort
        volumes:
            - "mongodb_data:/bitnami/mongodb"
    bot:
        container_name: phantomknight
        image: phantomknight/phantomknight:latest
        restart: unless-stopped
        volumes:
            - phantomknight-logs:/app/logs
        env_file:
            - .env
        environment:
            - token=$token
            - mongodbUrl=$mongodbUrl
            - clientId=$clientId
            - guildId=$guildId
            - topggtoken= $topggtoken
        stdin_open: true
        tty: true
        depends_on:
            - mongodb
volumes:
    phantomknight-logs:
    mongodb_data:
        driver: local
