name: Release

on:
    push:
        branches: ["main"]

jobs:
    docker:
        name: Publish Bot's Website Docker Image
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USER }}
                  -p ${{ secrets.DOCKER_PASS }}
            - name: Build Docker image
              run: docker build -t phantomknight/phantomknight-site:latest -t phantomknight/phantomknight-site:${GITHUB_SHA::8} ./client
            - name: Publish Docker image
              run: docker push phantomknight/phantomknight-site